name: mygame
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  video_player: ^2.8.6
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app-icon/ecomind-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.png
    - assets/images/bg1.jpg
    - assets/images/bg2.jpg
    - assets/images/bg3.jpg
    - assets/images/avatar.png
    - assets/images/logo.png
    - assets/videos/bg4.mp4
    - assets/images/bot.png
    - assets/icons/facebook.png
    - assets/icons/google.png
    - assets/icons/apple.png
    - assets/images/marketplace/bamboo-toothbrush.jpg
    - assets/images/marketplace/bamboo-cutlery.jpg
    - assets/images/marketplace/organic-tote-bag.jpg
    - assets/images/marketplace/recycled-sunglasses.jpg
    - assets/images/marketplace/Sandwich-Wrapped-Beeswax.jpg
    - assets/images/marketplace/shampoo-bar.jpg
    - assets/images/marketplace/stainless-water-bottle.jpg
    - assets/images/marketplace/swedish-dishcloth.jpg
    - assets/images/people/person1.jpg
    - assets/images/people/person2.jpg
    - assets/images/people/person3.jpg
    - assets/images/people/person4.jpg
    - assets/images/groups/eco-tunisia.jpg
    - assets/images/groups/tounes-tech.jpg
    - assets/images/groups/bac-2026-warriors.jpg
    - assets/images/groups/cat-lovers.jpg
    - assets/images/groups/tounes-gaming.jpg
    - assets/images/groups/startup-tunisia.jpg
    - assets/images/groups/movies-lovers-tn.jpg
    - assets/images/groups/9a3da-w-kresi.jpg
    - assets/images/posts/post1.jpg
    - assets/images/posts/post2.jpg
    - assets/app-icon/ecomind-circle.png
